---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: share-00
  labels:
    name: share-00
spec:
  capacity:
    storage: 1Gi
  storageClassName: ""
  accessModes:
  - ReadWriteMany
  nfs:
    path: "/mnt/share-00"
    server: fileserver
  persistentVolumeReclaimPolicy: Recycle
