#!/bin/bash
echo "Renewing the bearer token ..."
gcloud auth activate-service-account --key-file=$HOME/.kube/sa.json
new_token=$(gcloud auth print-access-token)
kubectl config set-credentials $(kubectl config get-contexts | grep '*' | awk '{print $4}') --token=$new_token
echo "Token renewed."
